[package]
name = "verus"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
sha256 = "1.1.4"
yansi = "0.5"
anstream = "0.3.2"

[dependencies.uuid]
version = "1.4.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[target."cfg(windows)".dependencies]
win32job = "1"

[build_dependencies]
regex = "1"